name: Extracting..

on: [push]

env:
  TZ: Asia/Kolkata
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget expect p7zip-full p7zip-rar

       
       - name: Clone Firm Extractor Source Code
         run: git clone https://github.com/erfanoabdi/firmware_extractor firmware_extractor
       
       - name: Setting up Extraction requirements
         run: |
              sudo chmod -R 777 firmware_extractor
              cd firmware_extractor
              sudo apt install unace unrar zip unzip p7zip-full p7zip-rar sharutils rar uudeview mpack arj cabextract rename
              sudo apt install liblzma-dev python-pip brotli lz4
              sudo pip install backports.lzma protobuf pycrypto
       
       - name: Download Stock Rom & Generate Images
         run: |
               cd firmware_extractor
               wget -o firmware.zip https://oxygenos.oneplus.net/OnePlus6Oxygen_22.Y.76_OTA_0760_all_2107130227_0263a33cf60f4185.zip
               sudo ./extractor.sh
       
       - name: Zip Aonly and upload 
         run: |
              cd firmware_extractor
              sudo chmod -R 777 out
              cd out
              zip -r9 kek.zip *
              curl bashupload.com -T kek.zip
         
            
